---
title: "forestplot"
author: "J Brophy"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    code_folding: hide
    highlight: tango
    theme: cerulean
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
link-citations: yes
linkcolor: red
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Hierarchical forest plot

### Load the data
The raw data comes from the NEJM PLATO article. The regional hierarchical intervals are calculated in the `meta.Rmd` program from a Bayesian analysis using `Jags`
```{r}
# "/Users/jay/Documents/cardiology/data/ticagrelor/programs"
data <- read.csv("plato_plotdata.csv", stringsAsFactors=FALSE)
## Labels defining subgroups are a little indented!
subgps <- c(3,4,7,8,11,12,15,16,19,20,23,24, 27,28,29)
data$Variable[subgps] <- paste("  ",data$Variable[subgps]) 
  
## Combine the count and percent column
np <- ifelse(!is.na(data$Count), paste(data$Count," (",round(data$Percent,2),")",sep=""), NA)
  
## The rest of the columns in the table. 
tabletext <- cbind(c("Region","\n",data$Variable), 
                    c("No. of Patients (%)","\n",np), 
                    c("Events\n Ticagrelor","\n",data$Ticagrelor), 
                    c("Events\n Clopidogrel","\n",data$Clopidogrel), 
                    c("P Value","\n",data$P.Value))

```

```{r}
library(forestplot)
png(file.path("Plato_good.png"),width=960, height=640)
forestplot(labeltext=tabletext, graph.pos=3, 
           mean=c(NA,NA,data$Point.Estimate), 
           lower=c(NA,NA,data$Low), upper=c(NA,NA,data$High),
           title="PLATO Geographic Variation",
           xlab="<--Ticagrelor Better           Clopidogrel Better-->                    ",
           hrzl_lines=list("2" = gpar(lwd=1, col="#99999922"), 
                          "5" = gpar(lwd=60, lineend="butt", columns=c(2:6), col="#99999922"),
                          "6" = gpar(lwd=60, lineend="butt", columns=c(2:6), col="#99999922"),
                          "9" = gpar(lwd=60, lineend="butt", columns=c(2:6), col="#99999922"),
                          "10" = gpar(lwd=60, lineend="butt", columns=c(2:6), col="#99999922"),
                          "13" = gpar(lwd=60, lineend="butt", columns=c(2:6), col="#99999922"),
                          "14" = gpar(lwd=60, lineend="butt", columns=c(2:6), col="#99999922"),
                          "17" = gpar(lwd=60, lineend="butt", columns=c(2:6), col="#99999922"),
                          "18" = gpar(lwd=60, lineend="butt", columns=c(2:6), col="#99999922"),
                          "21" = gpar(lwd=60, lineend="butt", columns=c(2:6), col="#99999922"),
                          "22" = gpar(lwd=60, lineend="butt", columns=c(2:6), col="#99999922"),
                          "25" = gpar(lwd=60, lineend="butt", columns=c(2:6), col="#99999922"),
                          "26" = gpar(lwd=60, lineend="butt", columns=c(2:6), col="#99999922"),
                          #"29" = gpar(lwd=60, lineend="butt", columns=c(2:6), col="#02552555"),
                          "30" = gpar(lwd=60, lineend="butt", columns=c(2:6), col="#02552555"),
                          "31" = gpar(lwd=60, lineend="butt", columns=c(2:6), col="#02552555")),
           txt_gp=fpTxtGp(label=gpar(cex=1.25),
                              ticks=gpar(cex=1.1),
                              xlab=gpar(cex = 1.2),
                              title=gpar(cex = 1.2)),
           col=fpColors(box="black", lines="red", zero = "gray50"),
           zero=1, cex=0.9, lineheight = "auto", boxsize=0.5, colgap=unit(6,"mm"),
           lwd.ci=2, ci.vertices=TRUE, ci.vertices.height = 0.4)
dev.off()
```

